#!/bin/bash

/home/androidbuilder/.cabal/bin/cabal --version
/home/androidbuilder/.cabal/bin/cabal --help

mkdir deps
cd deps
echo 'Installing text'
/home/androidbuilder/.cabal/bin/cabal get text-1.2.0.4
cd text-1.2.0.4
/home/androidbuilder/.ghc/android-host/bin/ghc Setup.lhs -o setup
./setup configure --verbose=3 --ghc --with-compiler=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc --prefix=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal --bindir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/bin --libdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/lib --libsubdir=arm-linux-android-ghc-7.8.3/text-1.0.0.0 --libexecdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/libexec --datadir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share --datasubdir=arm-linux-android-ghc-7.8.3/text-1.0.0.0 --docdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0 --htmldir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0/html --haddockdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0/html --sysconfdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/etc --configure-option=--host=arm-linux-androideabi --user --package-db=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/lib/arm-unknown-linux-androideabi-ghc-7.8.3/package.conf.d --flags=-integer-simple --flags=-developer --extra-prog-path=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/bin --disable-tests --disable-benchmarks --with-gcc=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-gcc --with-ghc=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc --with-ghc-pkg=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc-pkg --with-hsc2hs=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-hsc2hs --with-ld=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-ld --with-strip=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-strip --hsc2hs-option=--cross-compile
./setup build && ./setup install
echo 'text installed'
cd ..


echo 'Installing transformers'
/home/androidbuilder/.cabal/bin/cabal get transformers-0.4.2.0
cd transformers-0.4.2.0
/home/androidbuilder/.ghc/android-host/bin/ghc Setup.hs -o setup
./setup configure --verbose=3 --ghc --with-compiler=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc --prefix=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal --bindir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/bin --libdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/lib --libsubdir=arm-linux-android-ghc-7.8.3/text-1.0.0.0 --libexecdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/libexec --datadir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share --datasubdir=arm-linux-android-ghc-7.8.3/text-1.0.0.0 --docdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0 --htmldir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0/html --haddockdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0/html --sysconfdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/etc --configure-option=--host=arm-linux-androideabi --user --package-db=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/lib/arm-unknown-linux-androideabi-ghc-7.8.3/package.conf.d --flags=-integer-simple --flags=-developer --extra-prog-path=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/bin --disable-tests --disable-benchmarks --with-gcc=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-gcc --with-ghc=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc --with-ghc-pkg=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc-pkg --with-hsc2hs=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-hsc2hs --with-ld=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-ld --with-strip=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-strip --hsc2hs-option=--cross-compile
./setup build && ./setup install
echo 'transformers installed'
cd ..


echo 'Installing mtl'
/home/androidbuilder/.cabal/bin/cabal get mtl-2.2.1
cd mtl-2.2.1
/home/androidbuilder/.ghc/android-host/bin/ghc Setup.hs -o setup
./setup configure --verbose=3 --ghc --with-compiler=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc --prefix=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal --bindir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/bin --libdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/lib --libsubdir=arm-linux-android-ghc-7.8.3/text-1.0.0.0 --libexecdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/libexec --datadir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share --datasubdir=arm-linux-android-ghc-7.8.3/text-1.0.0.0 --docdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0 --htmldir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0/html --haddockdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0/html --sysconfdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/etc --configure-option=--host=arm-linux-androideabi --user --package-db=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/lib/arm-unknown-linux-androideabi-ghc-7.8.3/package.conf.d --flags=-integer-simple --flags=-developer --extra-prog-path=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/bin --disable-tests --disable-benchmarks --with-gcc=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-gcc --with-ghc=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc --with-ghc-pkg=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc-pkg --with-hsc2hs=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-hsc2hs --with-ld=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-ld --with-strip=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-strip --hsc2hs-option=--cross-compile
./setup build && ./setup install
echo 'mtl installed'
cd ..


echo 'Installing foreign-jni'
git clone https://github.com/neurocyte/foreign-jni.git
cd foreign-jni
/home/androidbuilder/.ghc/android-host/bin/ghc Setup.hs -o setup
./setup configure --verbose=3 --ghc --with-compiler=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc --prefix=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal --bindir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/bin --libdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/lib --libsubdir=arm-linux-android-ghc-7.8.3/text-1.0.0.0 --libexecdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/libexec --datadir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share --datasubdir=arm-linux-android-ghc-7.8.3/text-1.0.0.0 --docdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0 --htmldir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0/html --haddockdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/share/doc/arm-linux-android-ghc-7.8.3/text-1.0.0.0/html --sysconfdir=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/etc --configure-option=--host=arm-linux-androideabi --user --package-db=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/lib/arm-unknown-linux-androideabi-ghc-7.8.3/package.conf.d --flags=-integer-simple --flags=-developer --extra-prog-path=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/.cabal/bin --disable-tests --disable-benchmarks --with-gcc=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-gcc --with-ghc=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc --with-ghc-pkg=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-ghc-pkg --with-hsc2hs=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-unknown-linux-androideabi-hsc2hs --with-ld=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-ld --with-strip=/home/androidbuilder/.ghc/android-14/arm-linux-androideabi-4.8/bin/arm-linux-androideabi-strip --hsc2hs-option=--cross-compile
./setup build && ./setup install
echo 'foreign-jni installed'
cd ..
